# Generated by Django 5.0.13 on 2025-03-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loandata',
            old_name='hosue_number',
            new_name='house_number',
        ),
    ]
