# Generated by Django 5.0.13 on 2025-03-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapp_api', '0002_rename_hosue_number_loandata_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandata',
            name='loan_id',
            field=models.IntegerField(default='1234'),
        ),
    ]
